### ISSUE TITLE
tads command only produces output for one chromosome

### ISSUE THREAD

**Issue by gangxuehzau** [vaquerizaslab/tadtool#1]
Hi,
 I tried running the  **tadtool tads** to obtain the tads from my own matrix.Before that,I had running the **tadtool plot**which was running well.My matrix have five chromosomes,but the output file only include tads from chr1.
this is my code  

> tadtool tads 2X_100k.matrix.txt 2X_100k.bed 102353 340 my_TAD
> (the window size and cuttof refer to the **tadtool plot** )
> this is the running information
> 
> ```
> $ tadtool tads 2X_100k.matrix.txt 2X_100k.bed 102353 340.00 my_TAD
> 2016-07-20 15:32:02,597 INFO Loading matrix...
> 2016-07-20 15:32:05,311 INFO Loading regions...
> 2016-07-20 15:32:05,322 INFO Calculating index...
> tadtool l regions:  1193
> 2016-07-20 15:32:05,435 INFO Calling TADs
> L matrix, l regions:  1193 1193
> ```
> 
> thanks
> xue

**Comment by vaquerizaslab-old** [comment]
Hi there,

can you please upgrade TADtool to the latest version (0.61) and try running it again?

``` bash
pip install --upgrade tadtool
```

We fixed a similar issue with one of the last commits and that may have fixed yours along with it.

In any case, we **highly recommend** determining parameters and calling TADs on individual chromosomes only, as the contact probability decay with distance can vary quite a bit between chromosomes, especially if you used a matrix balancing method to correct your data. This will influence what parameters are robust for each chromosome.

**Comment by vaquerizaslab-old** [comment]
Hi again,

did this fix your problem? Then I will go ahead and close this issue.

Thanks

**Comment by gangxuehzau** [comment]
Hi,
I have fixed my problem ,thanks so much!
gangxue

At 2016-07-25 15:31:16, "vaquerizaslab" notifications@github.com wrote:

Hi again,

did this fix your problem? Then I will go ahead and close this issue.

Thanks

**Comment by MatStz** [comment]
Hi,

I have a very similar issue.

I tried to run tadool tads with two independent sets data. The output file always contains a list of TADS only for the first chromosome listed in the regions.bed file (chromosome 10 in one case, chromosome 1 in the other case). I do use the last version of tadtool (0.76).

Do you have any idea where this problem can come from? I of course checked that matrix files do contain whole genome data.

Thank you!

Mathias
