### ISSUE TITLE
Values IS in command "tads"

### ISSUE THREAD

**Issue by LeonardoLed** [vaquerizaslab/tadtool#14]
Hi there,
Good day, I have a question, is it possible to get out the values of Insulation Score when I put in console:
 `tadtool tads hg19_50000_chr6_dense.matrix chr6.bed 100000 16`

I understand that TADs will be written to the command line in this order:
Chromosome   START  END

I'm just wondering If there is a way that I can get the values IS:
Chromosome   START  END ValueIS

Thank you

**Comment by vaquerizaslab-old** [comment]
Hi,

the `-v` option of `tadtool tads` will do exactly that. You may have to upgrade to the latest version, then in your example above:

`tadtool tads -v hg19_50000_chr6_dense.matrix chr6.bed 100000 16`
