### ISSUE TITLE
Tadtool tads stops after processing one chromosome

### ISSUE THREAD

**Issue by MatStz** [vaquerizaslab/tadtool#16]
Hi,

I have a very similar issue than #1, please remove the post if you think it is necessary. 

I tried to run tadool tads with two independent sets data. The output file always contains a list of TADS only for the first chromosome listed in the regions.bed file (chromosome 10 in one case, chromosome 1 in the other case). I do use the last version of tadtool (0.76).

Do you have any idea where this problem can come from? I of course checked that matrix files do contain whole genome data.

Thank you!

Mathias

**Comment by vaquerizaslab-old** [comment]
We are working on this now, I'll update you as soon as we figure out what is going wrong!

**Comment by vaquerizaslab-old** [comment]
Can you please upgrade to the latest version (should already be available via `pip`) and let us know if that fixed the issue? Thanks!

**Comment by MatStz** [comment]
Hi

Seems to work well with the upgrade (0.77)

Thank you very much!

Mathias

**Comment by vaquerizaslab-old** [comment]
Thank you for reporting this issue and apologies for the complication!
