### ISSUE TITLE
Raw or Iced matrices as input?

### ISSUE THREAD

**Issue by rikrdo89** [vaquerizaslab/tadtool#20]
Hi, this is a question rather than an issue, but I wasn't able to find anything in the documentation regarding the type of matrix that would work better for identifying TADs using TADtool.  I have both raw and iced matrixes from HiC-pro pipeline. I suppose Iced matrices would be better since they are already normalized, but I want to make sure this is the case. Thank you.

**Comment by kaukrise** [comment]
Yes, use ICE-normalised matrices whenever possible. TADtool will also work
on raw counts matrices, but the TAD calls will be less affected by biases
when using normalised input!

**Comment by rikrdo89** [comment]
That's what I thought. Thank you! I have one more question/issue when loading matrices and bed files straight from HiC-pro... I get an error re:  "file cannot contain pickled data". I'll open a new issue.
