### ISSUE TITLE
Minor issue with progress bar

### ISSUE THREAD

**Issue by Krannich479** [vaquerizaslab/tadtool#4]
Hej, 
just in case someone traps into the same error:
I just pulled the latest git clone of TADtool today. It crashes with the latest release of progressbar-2.3 saying:

```
[...]/lib/python2.7/site-packages/tadtool/tad.py", line 630, in data_array
    pb = progressbar.ProgressBar(max_value=l)
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

The fix is a one-liner within the tad.py: 
`pb = progressbar.ProgressBar(maxval=l)`

**Comment by vaquerizaslab-old** [comment]
TADtool depends on progressbar2 (see setup.py), which is currently at version 3.10.1 - it seems you are using progressbar. progressbar has apparently not been maintained for a very long time.

The naming of the two packages, especially during import, is unfortunate. I recommend uninstalling progressbar and replacing it with progressbar2.

edit: added more info on the state of progressbar and a recommendation.

**Comment by kiranbeethoju** [comment]
@darshan3 changing max_value to maxval won't works in progressbar2,
The solution is uninstall existing progressbar by following below steps
sudo pip3 uninstall progressbar 
then install progressbar2 
then set max_value="your maxvalue"
run the python file by using python3.7
