### ISSUE TITLE
tadtool not loading automatically

### ISSUE THREAD

**Issue by farshadf** [vaquerizaslab/tadtool#6]
Hi,

After installation, the "tadtool" is not found automatically. Should I set up a path parameter?

**Comment by vaquerizaslab-old** [comment]
Hey,

I'm sorry to hear that the executable can't be found. Unfortunately, this sounds like it is not a problem we can help you with. The PATH should have been properly set up when you installed Python. If it wasn't, maybe you can find help on a Python forum.

Sorry
