### ISSUE TITLE
BED file should be 0-based, but examples here are 1-based

### ISSUE THREAD

**Issue by hansiu** [vaquerizaslab/tadtool#8]
Hey,

As detailed here:
https://genome.ucsc.edu/FAQ/FAQformat.html#format1 
BED format, including BED3 is 0-based:

- chromStart: The starting position of the feature in the chromosome or scaffold. **The first base in a chromosome is numbered 0.**

- chromEnd - The ending position of the feature in the chromosome or scaffold. **The chromEnd base is not included in the display of the feature. For example, the first 100 bases of a chromosome are defined as chromStart=0, chromEnd=100, and span the bases numbered 0-99**.

And in TADtool examples folder both BED files are 1-based (starting with one and the end is included).

So i.e the line:
chr12	19975001	20000000
should be:
chr12	19975000	20000000

I didn't check the rest of the code but probably this change could affect the algorithms too.

Letting you know to help avoid further users confusion :)

Thank you for developing TADtool!
Hania

**Comment by vaquerizaslab-old** [comment]
Dear Hania,

thank you for your detailed description of the issue. I have just uploaded the latest set of changes, which should also fix this issue. Example files are now BED3 compliant, as is the expected in- and output.

Let us know if you encounter any problems!
