### ISSUE TITLE
Problem with the format HiC matrix generated by HicPro

### ISSUE THREAD

**Issue by LeonardoLed** [vaquerizaslab/tadtool#9]
Hi there, I have a problem with TAD TOOL when I work with files generated by HicPro:

- MATRIX HIC 
-BED FILE

when I run this:
tadtool ploy myfile.matrix mybedfile.bed chr6:53700001-57250000
I got this message in console:

root@dgei 100000]# tadtool plot hg19_100000.matrix hg19_100000_ord.bed chr6:53700001-57250000
2017-11-05 00:19:16,321 INFO Loading regions...
2017-11-05 00:19:16,396 INFO Checking plotting region in matrix...
2017-11-05 00:19:16,398 INFO Loading matrix...
Traceback (most recent call last):
  File "/root/anaconda2/bin/tadtool", line 295, in <module>
    TADtool()
  File "/root/anaconda2/bin/tadtool", line 40, in __init__
    getattr(self, args.command)()
  File "/root/anaconda2/bin/tadtool", line 131, in plot
    matrix = tad.load_matrix(matrix_file, len(regions))
  File "/root/anaconda2/lib/python2.7/site-packages/tadtool/tad.py", line 266, in load_matrix
    m[source, sink] = weight
IndexError: index 30971 is out of bounds for axis 1 with size 30971

any idea in order to solve the problem?

my files have this format:

[root@dgei 100000]# tail hg19_100000.matrix 
30632	30971	1
30662	30662	2
30662	30966	19
30662	30967	11
30966	30966	738
30966	30967	440
30966	30971	20
30967	30967	652
30967	30971	11
30971	30971	38395

[root@dgei 100000]# head hg19_100000_abs.bed 
chr1	0	100000	1
chr1	100000	200000	2
chr1	200000	300000	3
chr1	300000	400000	4
chr1	400000	500000	5
chr1	500000	600000	6
chr1	600000	700000	7
chr1	700000	800000	8
chr1	800000	900000	9
chr1	900000	1000000	10

Thanks a lot

**Comment by vaquerizaslab-old** [comment]
Hi there,

please ensure that you are running the latest version of TADtool. This looks like a problem that has been fixed a couple of months ago (also the line numbers in your error messages don't match with the latest available code).

A quick way of obtaining the latest version is by uninstalling the old version and then getting the latest version with pip:

```
pip uninstall tadtool
pip install tadtool
```

Or, if you are not the owner of the Python installation:

```
pip uninstall tadtool
pip install --user tadtool
```


Please let me know if the problem persists after that.

**Comment by LeonardoLed** [comment]
Thanks a lot, It works
